# Generated by Django 3.2.7 on 2021-10-01 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_player_height'),
        ('league', '0003_alter_gameteam_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='win_team',
        ),
        migrations.RemoveField(
            model_name='gameteam',
            name='score',
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_played', to='teams.player'),
        ),
        migrations.AddField(
            model_name='gameteam',
            name='result',
            field=models.CharField(choices=[('Won', 'Won'), ('Lost', 'Lost')], max_length=5, null=True),
        ),
    ]
